name: Post Instagram Saying

on:
  schedule:
    - cron: '0 7 * * *'   # 09:00 Europe/Amsterdam = 07:00 UTC (adjust for DST if needed)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow requests

      - name: Render image from CSV
        id: render
        env:
          CSV_PATH: content/sayings.csv
          OUT_DIR: public/instagram
        run: |
          python render_post.py >> $GITHUB_OUTPUT

      - name: Stop if nothing to post
        if: steps.render.outputs.no_row == 'true'
        run: echo "No row to post today."

      - name: Commit new image
        if: steps.render.outputs.image_rel_path
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/instagram
          git commit -m "Add Instagram image: ${GITHUB_RUN_ID}" || echo "Nothing to commit"
          git push

      - name: Publish to Instagram
        if: steps.render.outputs.image_rel_path
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME:  ${{ github.event.repository.name }}
          BRANCH:     ${{ github.ref_name }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          PAGE_TOKEN: ${{ secrets.PAGE_TOKEN }}
          CSV_PATH:   content/sayings.csv
          IMAGE_REL_PATH: ${{ steps.render.outputs.image_rel_path }}
          CAPTION: ${{ steps.render.outputs.caption }}
          ROW_ID:  ${{ steps.render.outputs.row_id }}
        run: |
          python publish_instagram.py

      - name: Commit CSV status update
        if: steps.render.outputs.image_rel_path
        run: |
          git add content/sayings.csv
          git commit -m "Mark posted: ${{ steps.render.outputs.row_id }}" || echo "Nothing to commit"
          git push
